### ISSUE TITLE
There is support for LAUNCHXL_CC2650 ?

### ISSUE THREAD

**Issue by lcgamboa** [biagiom/cc26xx-core#1]
Is there support for the LAUNCHXL CC2650? Is it possible to change the code to work with LAUNCHXL_CC2650? The code works on Energia 1.6.10E18?

Thank you for your attention.

**Comment by biagiom** [comment]
Hi @lcgamboa and sorry for my late reply.
The cc26xx-core only support the TI CC2650 SensorTag but there are also some issues (Serial communication is not working properly).
Support for the LAUNCHXL CC2650 could be integrated adding some changes to the code (the cc26xx-core is based on [cc13xx-core](https://github.com/energia/cc13xx-core) which supports the CC1310 and CC1350 SensorTag and also Lanuchpad but there are also [some issues](https://github.com/energia/cc13xx-core/issues)), but the main issue is getting the radio interface working. Support for CC2650 MCU was initially added to Energia project but because of the incompatibility of the BLE stack's license with the one of the Energia project,  it has been removed from Energia, in fact starting from version 1.6.10E18, Energia no longer supports the CC2650 SensorTag (see: [#912](https://github.com/energia/Energia/issues/912), [#740](https://github.com/energia/Energia/issues/740)).
The cc26xx-core should work with the 1.6.10E18 version.
I have also wrote a [post](https://forum.43oh.com/topic/10485-energia-board-support-package-for-cc2650-sensortag/) on the 430oh forum about the cc26xx-core BSP but I haven't received any reply yet.
Best regards.
